version: "3.7"
services:
  #client:
  #  build: ./client
  #  ports:
  #    - "8082:3000"

  # mongo:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  # mongo-express:
  #   image: mongo-express
  #   environment:
  #     ME_CONFIG_MONGODB_PORT: 27017
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongo
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    hostname: pgAdmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 3001:80
    restart: always

  common_tenant:
    image: postgres
    container_name: common_tenant
    hostname: common_tenant
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: common_tenant
    volumes:
      - ./initCommon.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - 5432:5432

  tenant1:
    image: postgres
    container_name: tenant1
    hostname: tenant1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tenant1
    volumes:
      - ./initTenant1.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - 5433:5432

  tenant2:
    image: postgres
    container_name: tenant2
    hostname: tenant2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tenant2
    volumes:
      - ./initTenant2.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - 5434:5432

  tenant3:
    image: mcr.microsoft.com/mssql/server
    container_name: tenant3
    hostname: tenant3
    environment:
      SA_PASSWORD: saPower_123
      ACCEPT_EULA: Y
    volumes:
      - ./initTenant3.sql:/scripts/init.sql
    restart: always
    ports:
      - 1433:1433
    command:
      - /bin/bash
      - -c 
      - |
        # Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &
        # Wait 30 seconds for it to be available
        # (lame, I know, but there's no nc available to start prodding network ports)
        sleep 100
        # Run every script in /scripts
        /opt/mssql-tools/bin/sqlcmd -U sa -P saPower_123 -l 30 -e -i /scripts/init.sql
        # So that the container doesn't shut down, sleep this thread
        sleep infinity

#  server:
#    build: ./server
#    container_name: server
#    hostname: server
#    environment: 
#      - PORT=5000
#      - NODE_ENV=production
      #- MONGO_SERVER=mongo
#      - TENANT_CLIENT=pg
#      - TENANT_USER=postgres
#      - TENANT_PORT=5432
#      - TENANT_HOST=common_tenant
#      - TENANT_DATABASE=common_tenant
#      - TENANT_PASSWORD=postgres
#    ports:
#      - "5000:5000"
#    depends_on:
#      - common_tenant